# Generate stack secrets
- name: Generate stack secrets
  block:
    # Define database credentials
    # Dynamically generates and sets database credentials including username, database name, and a secure password.
    - set_fact:
        db:
          username: postgres
          db_name: keycloak
          password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=32) | trim }}"

    # Check database user credentials
    # Verifies that database credentials are correctly defined and non-empty.
    - assert:
        that:
          - db.username is defined
          - db.username != ''
          - db.password is defined
          - db.password != ''
          - db.db_name is defined
          - db.db_name != ''
        fail_msg: "Database credentials assertion failed"
        success_msg: "Ok"

    # Define Keycloak credentials
    # Dynamically generates and sets Keycloak credentials, including admin and testing realm details.
    - set_fact:
        keycloak:
          client_id: admin-cli
          auth_url: "http://localhost:8080"
          auth_realm: "master"
          username: admin
          password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=32) | trim }}"
          testing_realm_client_id: app_client
          testing_realm_auth_client_id: "auth_client"
          testing_realm_auth_client_secret: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=32) | trim }}"
          testing_realm_admin:
            username: "{{ realm }}_admin"
            password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits','punctuation'], length=32) | trim }}"
            email: "admin@example.com"
            firstName: "John"
            lastName: "Doe"

    # Check Keycloak admin credentials
    # Verifies that Keycloak admin and testing realm credentials are correctly defined and non-empty.
    - assert:
        that:
          - keycloak.client_id is defined
          - keycloak.client_id != ''
          - keycloak.auth_url is defined
          - keycloak.auth_url != ''
          - keycloak.auth_realm is defined
          - keycloak.auth_realm != ''
          - keycloak.username is defined
          - keycloak.username != ''
          - keycloak.password is defined
          - keycloak.password != ''
          - keycloak.testing_realm_client_id is defined
          - keycloak.testing_realm_client_id != ''
          - keycloak.testing_realm_auth_client_id is defined
          - keycloak.testing_realm_auth_client_id != ''
          - keycloak.testing_realm_auth_client_secret is defined
          - keycloak.testing_realm_auth_client_secret != ''
          - keycloak.testing_realm_admin is defined
          - keycloak.testing_realm_admin.username is defined
          - keycloak.testing_realm_admin.username != ''
          - keycloak.testing_realm_admin.password is defined
          - keycloak.testing_realm_admin.password != ''
          - keycloak.testing_realm_admin.email is defined
          - keycloak.testing_realm_admin.email != ''
          - keycloak.testing_realm_admin.firstName is defined
          - keycloak.testing_realm_admin.firstName != ''
          - keycloak.testing_realm_admin.lastName is defined
          - keycloak.testing_realm_admin.lastName != ''
        fail_msg: "Keycloak credentials assertion failed"
        success_msg: "Ok"
