# Create audiences
# Configures a Keycloak client scope for managing OIDC audiences in the specified realm.
- name: "Create realm {{ realm }} audiences client scope"
  community.general.keycloak_clientscope:
    auth_client_id: "{{ keycloak.client_id }}"
    auth_keycloak_url: "{{ keycloak.auth_url }}"
    auth_realm: "{{ keycloak.auth_realm }}"
    auth_username: "{{ keycloak.username }}"
    auth_password: "{{ keycloak.password }}"
    realm: "{{ realm }}"
    name: audiences
    description: oidc audiences
    protocol: openid-connect
    attributes:
      include.in.token.scope: 'true'
      display.on.consent.screen: 'false'
      gui.order: ''
      consent.screen.text: ''
    protocol_mappers:
    - name: app_client audience mapper
      protocol: openid-connect
      protocolMapper: oidc-audience-mapper
      config:
        included.client.audience: app_client
        id.token.claim: 'false'
        access.token.claim: 'true'
  retries: 5
