# Load realm variables
# Loads Keycloak realm configuration variables from a predefined file.
- include_vars:
    file: "vars/kc_realm.yml"

# Set the old password policy
# This policy uses a higher iteration count (27500) for hashing and includes requirements for length, special characters, uppercase, lowercase, digits, and password history.
- set_fact:
    old_password_policy: "hashIterations(27500) and length(10) and notUsername(undefined) and notEmail(undefined) and specialChars(1) and upperCase(1) and lowerCase(1) and digits(1) and passwordHistory(12)"

# Set the argon password policy
# This policy uses a lower iteration count (99) for hashing while maintaining the same requirements for length, special characters, uppercase, lowercase, digits, and password history.
- set_fact:
    argon_password_policy: "hashIterations(99) and length(10) and notUsername(undefined) and notEmail(undefined) and specialChars(1) and upperCase(1) and lowerCase(1) and digits(1) and passwordHistory(12)"

# Set the active password policy based on the Keycloak version
# If the Keycloak version is not in ['20.0.3', '22.0.3', '21.1.2', '23.0.7'], the argon password policy is used; otherwise, the old password policy is applied.
- set_fact:
    password_policy: "{{ argon_password_policy if ((kc_version | default('')) not in ['20.0.3', '22.0.3', '21.1.2', '23.0.7', '24.0.5-0']) else old_password_policy }}"


# Create Keycloak realm
# Configures a new Keycloak realm or updates an existing one with the specified settings.
- name: "Create {{ realm }} realm"
  community.general.keycloak_realm:
    auth_client_id: "{{ keycloak.client_id }}"
    auth_keycloak_url: "{{ keycloak.auth_url }}"
    auth_realm: "{{ keycloak.auth_realm }}"
    auth_username: "{{ keycloak.username }}"
    auth_password: "{{ keycloak.password }}"
    id: "{{ id }}"
    realm: "{{ realm }}"
    attributes: "{{ attributes }}"
    access_code_lifespan: "{{ access_code_lifespan }}"
    access_code_lifespan_login: "{{ access_code_lifespan_login }}"
    access_token_lifespan_for_implicit_flow: "{{ access_token_lifespan_for_implicit_flow }}"
    action_token_generated_by_admin_lifespan: "{{ action_token_generated_by_admin_lifespan }}"
    action_token_generated_by_user_lifespan: "{{ action_token_generated_by_user_lifespan }}"
    browser_flow: "{{ browser_flow }}"
    client_authentication_flow: "{{ client_authentication_flow }}"
    default_signature_algorithm: "{{ default_signature_algorithm }}"
    direct_grant_flow: "{{ direct_grant_flow }}"
    docker_authentication_flow: "{{ docker_authentication_flow }}"
    duplicate_emails_allowed: "{{ duplicate_emails_allowed }}"
    edit_username_allowed: "{{ edit_username_allowed }}"
    enabled: "{{ enabled }}"
    login_with_email_allowed: "{{ login_with_email_allowed }}"
    offline_session_idle_timeout: "{{ offline_session_idle_timeout }}"
    offline_session_max_lifespan: "{{ offline_session_max_lifespan }}"
    offline_session_max_lifespan_enabled: "{{ offline_session_max_lifespan_enabled }}"
    password_policy: "{{ password_policy }}"
    refresh_token_max_reuse: "{{ refresh_token_max_reuse }}"
    registration_allowed: "{{ registration_allowed }}"
    registration_email_as_username: "{{ registration_email_as_username }}"
    registration_flow: "{{ registration_flow }}"
    remember_me: "{{ remember_me }}"
    reset_credentials_flow: "{{ reset_credentials_flow }}"
    reset_password_allowed: "{{ reset_password_allowed }}"
    revoke_refresh_token: "{{ revoke_refresh_token }}"
    ssl_required: "{{ ssl_required }}"
    sso_session_idle_timeout: "{{ sso_session_idle_timeout }}"
    sso_session_idle_timeout_remember_me: "{{ sso_session_idle_timeout_remember_me }}"
    sso_session_max_lifespan: "{{ sso_session_max_lifespan }}"
    sso_session_max_lifespan_remember_me: "{{ sso_session_max_lifespan_remember_me }}"
    user_managed_access_allowed: "{{ user_managed_access_allowed }}"
    verify_email: "{{ verify_email }}"
    otp_policy_algorithm: "{{ otp_policy_algorithm }}"
    otp_policy_digits: "{{ otp_policy_digits }}"
    otp_policy_initial_counter: "{{ otp_policy_initial_counter }}"
    otp_policy_look_ahead_window: "{{ otp_policy_look_ahead_window }}"
    otp_policy_period: "{{ otp_policy_period }}"
    otp_policy_type: "{{ otp_policy_type }}"
    brute_force_protected: "{{ brute_force_protected }}"
    max_failure_wait_seconds: "{{ max_failure_wait_seconds }}"
    wait_increment_seconds: "{{ wait_increment_seconds }}"
    failure_factor: "{{ failure_factor }}"
    permanent_lockout: "{{ permanent_lockout }}"
    quick_login_check_milli_seconds: "{{ quick_login_check_milli_seconds }}"
    minimum_quick_login_wait_seconds: "{{ minimum_quick_login_wait_seconds }}"
    browser_security_headers: "{{ browser_security_headers }}"
    events_enabled: "{{ events_enabled }}"
    events_expiration: "{{ events_expiration }}"
    admin_events_enabled: "{{ admin_events_enabled }}"
    admin_events_details_enabled: "{{ admin_events_details_enabled }}"
    enabled_event_types: "{{ enabled_event_types }}"
    events_listeners: "{{ events_listeners }}"
    state: "{{ state }}"
  retries: 5
