# Create containers directory
# Ensures the containers directory is created with the specified properties.
- name: Create containers directory
  file:
    path: "{{ containers_dir }}/volumes/nginx"
    state: directory
    recurse: true
    force: true

# Generate services environments
# Renders environment configuration files for services using templates and places them in the containers directory.
- name: Generate services environments
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ containers_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - compose.yml
    - keycloak.env
    - postgres.env

# Copy nginx configuration to volumes
# Nginx configuration file will be used as fake endpoints during the tests
- name: Copy nginx configuration to volumes
  copy:
    src: "files/nginx.default.conf"
    dest: "{{ containers_dir }}/volumes/nginx/default.conf"
    mode: "0644"