name: Build
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
    branches:
      - master

jobs:
  # Build source code
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Setup .NET SDK
      - name: Set up .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      # Set Global.json to Match .NET SDK
      - name: Set .NET SDK Version
        run: |
          echo '{ "sdk": { "version": "${{ matrix.dotnet-version }}" } }' > global.json

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --no-restore -c Release
