name: Build test and analyze
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  # Build test and analyze source code
  build_test_analyze:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java-version: [21]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup OpenJDK
      - name: Setup OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java-version }}

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install all required .NET SDK versions
      - name: Install .NET SDKs (8.0, 9.0 and 10.0)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt install -y make python3-rpm
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global Cake.Tool
          dotnet tool install --global JetBrains.dotCover.CommandLineTools

      # Build test and analyze the project
      - name: Build test and analyze the project
        if: success()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          VIRTUAL_ENV_DIR: keycloak.venv
        run: |
          # Copy Licence
          cp LICENSE NETCore.Keycloak.Client/

          # Build, test and analyze project with keycloak version 26
          cd NETCore.Keycloak.Client.Tests
          dotnet cake build_test_analyse.cake --kc_major_version=26 --sonar_token=${SONAR_TOKEN}
