name: Build
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
    branches:
      - master

jobs:
  # Build source code
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [8.0.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Setup .NET SDK
      - name: Set up .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      # Setup cake tool
      - name: Setup cake tool
        run: |
          dotnet tool install --global Cake.Tool

      # Build the project
      - name: Build project
        run: dotnet cake cake.build
